# Generated by Django 4.2.6 on 2023-10-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0007_alter_sitefiles_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField(unique=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_links', to='sites.sitefiles')),
            ],
        ),
    ]
