# Generated by Django 4.2.6 on 2023-10-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_sitefiles_file'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='links',
        ),
        migrations.AlterField(
            model_name='link',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.sitefiles'),
        ),
        migrations.AddField(
            model_name='link',
            name='links',
            field=models.ManyToManyField(related_name='related_links', to='links.somelinks'),
        ),
    ]
