# Generated by Django 4.2.6 on 2023-10-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_somelinks_remove_link_links_alter_link_site_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somelinks',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
