# Generated by Django 4.2.6 on 2023-10-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='siteUrl',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
