# Generated by Django 4.2.6 on 2023-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionAnswer', '0002_remove_questionanswer_site_id'),
        ('sites', '0004_alter_site_siteurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
