# Generated by Django 4.2.6 on 2023-10-20 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_sitefiles_delete_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefiles',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitefiles',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitefiles',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitefiles',
            name='file',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
