# Generated by Django 4.2.6 on 2023-10-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_sitefiles_is_published_sitefiles_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefiles',
            name='file',
            field=models.FileField(upload_to='site_files'),
        ),
    ]
